import { getSupabaseClient, isSupabaseConfigured } from '../lib/supabase';
import {
  AreaRecord,
  ChartOfAccountRecord,
  CustomerDbRecord,
  MemberRegistrationRecord,
  MemberDbRecord,
  ProductDbRecord,
  RolePermissionRecord,
  SupplierDbRecord,
  TransactionCategoryRecord,
  UserRoleRecord,
  SupabaseTableName,
} from '../types/database';

export interface TableAuditInfo {
  tableName: SupabaseTableName;
  label: string;
  columnCount: number;
  columnsList: string[];
  isConfigured: boolean;
  isConnected: boolean;
  rowCount: number;
  latencyMs: number;
  statusMessage: string;
  lastChecked: string;
}

export const SUPABASE_TABLES_METADATA: Record<
  SupabaseTableName,
  { label: string; columnCount: number; columns: string[]; primaryKey: string; ddlSql: string }
> = {
  areas: {
    label: 'Wilayah & Cabang (Areas)',
    columnCount: 16,
    columns: [
      'id', 'referral_type', 'kopwil', 'area_code', 'area_name', 'bank_account_1',
      'bank_account_2', 'bank_account_3', 'province', 'city', 'sk_number',
      'potential', 'pic_name', 'pic_contact', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referral_type VARCHAR(30) DEFAULT 'KOPERASI',
  kopwil VARCHAR(100) DEFAULT '',
  area_code VARCHAR(50) NOT NULL UNIQUE,
  area_name VARCHAR(255) NOT NULL,
  bank_account_1 TEXT DEFAULT '',
  bank_account_2 TEXT DEFAULT '',
  bank_account_3 TEXT DEFAULT '',
  province VARCHAR(100) DEFAULT 'DKI Jakarta',
  city VARCHAR(150) DEFAULT 'Jakarta Pusat',
  sk_number VARCHAR(150) DEFAULT '',
  potential TEXT DEFAULT '',
  pic_name VARCHAR(150) DEFAULT '',
  pic_contact VARCHAR(100) DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  transaction_categories: {
    label: 'Kategori Transaksi (Transaction Categories)',
    columnCount: 8,
    columns: [
      'id', 'type', 'category_code', 'name', 'account_code', 'account_name', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.transaction_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(10) NOT NULL,
  category_code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  account_code TEXT,
  account_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  chart_of_accounts: {
    label: 'Bagan Akun (Chart of Accounts)',
    columnCount: 11,
    columns: [
      'id', 'account_code', 'account_name', 'account_group', 'financial_report',
      'normal_balance', 'tx_type', 'parent_code', 'is_active', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.chart_of_accounts (
  id TEXT PRIMARY KEY,
  account_code TEXT NOT NULL UNIQUE,
  account_name TEXT NOT NULL,
  account_group TEXT NOT NULL,
  financial_report TEXT NOT NULL,
  normal_balance TEXT NOT NULL CHECK (normal_balance IN ('Debit', 'Kredit')),
  tx_type TEXT DEFAULT 'UMUM',
  parent_code TEXT DEFAULT '',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  customers: {
    label: 'Pelanggan & Buyer (Customers)',
    columnCount: 15,
    columns: [
      'id', 'customer_code', 'name', 'pic_name', 'phone', 'email', 'address',
      'province', 'city', 'tax_number', 'category', 'status', 'notes', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.customers (
  id TEXT PRIMARY KEY,
  customer_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  pic_name TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  address TEXT DEFAULT '',
  province TEXT DEFAULT 'DKI Jakarta',
  city TEXT DEFAULT 'Jakarta',
  tax_number TEXT DEFAULT '',
  category TEXT DEFAULT 'Retail',
  status TEXT DEFAULT 'AKTIF',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  member_registrations: {
    label: 'Pendaftaran Anggota (Registrations)',
    columnCount: 22,
    columns: [
      'id', 'submitted_at', 'full_name', 'nik', 'birth_place', 'birth_date', 'gender',
      'address', 'city', 'province', 'whatsapp', 'email', 'member_status', 'profession',
      'savings_type', 'transfer_amount', 'transfer_date', 'transfer_proof_url', 'ktp_url',
      'selfie_url', 'approval_status', 'verification_status',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.member_registrations (
  id TEXT PRIMARY KEY,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  full_name TEXT NOT NULL,
  nik VARCHAR(16) NOT NULL,
  birth_place TEXT DEFAULT '',
  birth_date DATE DEFAULT '1990-01-01',
  gender VARCHAR(10) DEFAULT 'L',
  address TEXT DEFAULT '',
  city TEXT DEFAULT 'Jakarta',
  province TEXT DEFAULT 'DKI Jakarta',
  whatsapp TEXT NOT NULL,
  email TEXT DEFAULT '',
  member_status TEXT DEFAULT 'Calon Anggota',
  profession TEXT DEFAULT 'Wiraswasta',
  savings_type TEXT DEFAULT 'Pokok + Wajib',
  transfer_amount NUMERIC(15,2) DEFAULT 860000.00,
  transfer_date DATE DEFAULT CURRENT_DATE,
  transfer_proof_url TEXT DEFAULT '',
  ktp_url TEXT DEFAULT '',
  selfie_url TEXT DEFAULT '',
  approval_status TEXT DEFAULT 'PENDING' CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
  verification_status TEXT DEFAULT 'Menunggu Verifikasi Admin'
);`,
  },
  members: {
    label: 'Data Anggota Tetap (Members)',
    columnCount: 18,
    columns: [
      'id', 'member_no', 'registered_at', 'full_name', 'gender', 'province', 'city',
      'address', 'occupation', 'username', 'birth_date', 'birth_place', 'nik',
      'work_area', 'legacy_password_hash', 'status', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.members (
  id TEXT PRIMARY KEY,
  member_no TEXT NOT NULL UNIQUE,
  registered_at DATE DEFAULT CURRENT_DATE,
  full_name TEXT NOT NULL,
  gender VARCHAR(10) DEFAULT 'L' CHECK (gender IN ('L', 'P')),
  province TEXT DEFAULT 'DKI Jakarta',
  city TEXT DEFAULT 'Jakarta Pusat',
  address TEXT DEFAULT '',
  occupation TEXT DEFAULT 'Anggota',
  username TEXT UNIQUE,
  birth_date DATE DEFAULT '1990-01-01',
  birth_place TEXT DEFAULT 'Jakarta',
  nik VARCHAR(16) NOT NULL UNIQUE CHECK (nik ~ '^[0-9]{16}$'),
  work_area TEXT DEFAULT 'PUSAT JAKARTA',
  legacy_password_hash TEXT DEFAULT '',
  status TEXT DEFAULT 'AKTIF' CHECK (status IN ('AKTIF', 'NONAKTIF', 'PENDING', 'SUSPENDED')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  products: {
    label: 'Komoditas & Produk (Products)',
    columnCount: 12,
    columns: [
      'id', 'sku_code', 'sku_name', 'group_id', 'group_name', 'subgroup',
      'brand', 'grade', 'packaging', 'availability', 'moq', 'supply_capacity',
    ],
    primaryKey: 'sku_code',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.products (
  id TEXT,
  sku_code TEXT PRIMARY KEY,
  sku_name TEXT NOT NULL,
  group_id TEXT,
  group_name TEXT NOT NULL,
  subgroup TEXT DEFAULT '',
  brand TEXT DEFAULT 'Kopsim Mandiri',
  grade TEXT DEFAULT 'Grade A',
  packaging TEXT DEFAULT 'Standard',
  availability TEXT DEFAULT 'Tersedia',
  moq INT DEFAULT 1,
  supply_capacity TEXT DEFAULT '10 Ton/Bulan',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index percepatan query per Sektor Proyek Riil (group_name)
CREATE INDEX IF NOT EXISTS idx_products_group_name ON public.products (group_name);
CREATE INDEX IF NOT EXISTS idx_products_sku_name ON public.products (sku_name);`,
  },
  role_permissions: {
    label: 'Hak Akses Role (Role Permissions)',
    columnCount: 3,
    columns: ['id', 'role_name', 'permissions'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.role_permissions (
  id TEXT PRIMARY KEY,
  role_name TEXT NOT NULL UNIQUE,
  permissions JSONB DEFAULT '[]'::jsonb
);`,
  },
  suppliers: {
    label: 'Pemasok & Mitra Nelayan (Suppliers)',
    columnCount: 15,
    columns: [
      'id', 'supplier_code', 'name', 'pic_name', 'phone', 'email', 'address',
      'province', 'city', 'tax_number', 'category', 'status', 'notes', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.suppliers (
  id TEXT PRIMARY KEY,
  supplier_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  pic_name TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  address TEXT DEFAULT '',
  province TEXT DEFAULT 'DKI Jakarta',
  city TEXT DEFAULT 'Jakarta',
  tax_number TEXT DEFAULT '',
  category TEXT DEFAULT 'Hasil Laut',
  status TEXT DEFAULT 'AKTIF',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  transactions: {
    label: 'Transaksi & Keuangan (Transactions)',
    columnCount: 19,
    columns: [
      'id', 'transaction_no', 'transaction_date', 'referral_type', 'area_name',
      'transaction_type', 'payment_method', 'amount', 'file_url', 'account_name_legacy',
      'description', 'category_name', 'product_name', 'supplier_name', 'customer_name',
      'qty', 'price', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.transactions (
  id TEXT PRIMARY KEY,
  transaction_no TEXT NOT NULL UNIQUE,
  transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
  referral_type TEXT NOT NULL DEFAULT 'KOPERASI' CHECK (referral_type IN ('KOPERASI', 'PROJECT')),
  area_name TEXT NOT NULL DEFAULT 'PUSAT JAKARTA',
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('MASUK', 'KELUAR')),
  payment_method TEXT NOT NULL DEFAULT 'Bank BSI',
  amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0),
  file_url TEXT DEFAULT '',
  account_name_legacy TEXT DEFAULT 'Bank BSI',
  description TEXT DEFAULT '',
  category_name TEXT DEFAULT 'Kas',
  product_name TEXT DEFAULT '',
  supplier_name TEXT DEFAULT '',
  customer_name TEXT DEFAULT '',
  qty NUMERIC(12, 2) DEFAULT 1.00,
  price NUMERIC(15, 2) DEFAULT 0.00,
  member_id TEXT REFERENCES public.members(id) ON DELETE SET NULL,
  category_code TEXT REFERENCES public.transaction_categories(category_code) ON DELETE SET NULL,
  account_code TEXT REFERENCES public.chart_of_accounts(account_code) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  user_roles: {
    label: 'Peran Pengguna (User Roles)',
    columnCount: 4,
    columns: ['id', 'user_id', 'role', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.user_roles (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'DIRECTOR', 'ANGGOTA')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  news_articles: {
    label: 'Kanal Berita & Warta (News Articles)',
    columnCount: 13,
    columns: [
      'id', 'kategori', 'project_id', 'judul', 'ringkasan', 'konten', 'lokasi',
      'foto_url', 'tanggal', 'dibuat_oleh', 'status', 'created_at', 'updated_at',
    ],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.news_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kategori VARCHAR(50) NOT NULL CHECK (kategori IN ('kemitraan', 'program', 'dampak', 'update_proyek')),
  project_id VARCHAR(50),
  judul VARCHAR(255) NOT NULL,
  ringkasan TEXT NOT NULL,
  konten TEXT NOT NULL,
  lokasi VARCHAR(150),
  foto_url TEXT,
  tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
  dibuat_oleh UUID,
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'terbit')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  project_updates: {
    label: 'Log Perkembangan Proyek (Project Updates)',
    columnCount: 8,
    columns: ['id', 'project_id', 'judul', 'narasi', 'foto_url', 'tanggal', 'dibuat_oleh', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.project_updates (
  id VARCHAR(50) PRIMARY KEY,
  project_id VARCHAR(50) NOT NULL,
  judul VARCHAR(255) NOT NULL,
  narasi TEXT NOT NULL,
  foto_url TEXT,
  tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
  dibuat_oleh UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  profiles: {
    label: 'Profil Pengurus (Profiles)',
    columnCount: 7,
    columns: ['id', 'full_name', 'role', 'phone', 'avatar_url', 'created_at', 'updated_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY,
  full_name VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'ANGGOTA' CHECK (role IN ('ADMIN', 'DIRECTOR', 'ANGGOTA')),
  phone VARCHAR(50),
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  roles: {
    label: 'Master Peran (Roles)',
    columnCount: 4,
    columns: ['id', 'name', 'description', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  audit_logs: {
    label: 'Jejak Audit & Aktivitas (Audit Logs)',
    columnCount: 9,
    columns: ['id', 'user_id', 'user_email', 'action', 'entity', 'entity_id', 'old_values', 'new_values', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  user_email VARCHAR(150),
  action VARCHAR(100) NOT NULL,
  entity VARCHAR(100) NOT NULL,
  entity_id VARCHAR(100),
  old_values JSONB,
  new_values JSONB,
  ip_address VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  payment_requests: {
    label: 'Gerbang Pembayaran & QRIS/VA (Payment Requests)',
    columnCount: 16,
    columns: ['id', 'order_id', 'idempotency_key', 'member_id', 'member_name', 'amount', 'fee', 'total_amount', 'payment_type', 'payment_channel', 'status', 'expiry_time', 'paid_at', 'posted_transaction_id', 'webhook_attempts', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.payment_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id VARCHAR(100) NOT NULL UNIQUE,
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  member_id VARCHAR(50) NOT NULL,
  member_name VARCHAR(255) NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  fee NUMERIC(15,2) DEFAULT 0,
  total_amount NUMERIC(15,2) NOT NULL,
  payment_type VARCHAR(50) NOT NULL,
  payment_channel VARCHAR(50) NOT NULL,
  status VARCHAR(30) DEFAULT 'PENDING',
  expiry_time TIMESTAMPTZ NOT NULL,
  paid_at TIMESTAMPTZ,
  posted_transaction_id VARCHAR(100),
  webhook_attempts INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  notification_jobs: {
    label: 'Antrean Notifikasi Multi-Channel (Notification Jobs)',
    columnCount: 13,
    columns: ['id', 'type', 'recipient', 'recipient_name', 'channel', 'provider', 'payload', 'status', 'attempts', 'max_attempts', 'idempotency_key', 'sent_at', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.notification_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type VARCHAR(100) NOT NULL,
  recipient VARCHAR(255) NOT NULL,
  recipient_name VARCHAR(255),
  channel VARCHAR(50) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  payload JSONB NOT NULL,
  status VARCHAR(30) DEFAULT 'PENDING',
  attempts INT DEFAULT 0,
  max_attempts INT DEFAULT 3,
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  user_notifications: {
    label: 'Kotak Masuk Anggota (User In-App Notifications)',
    columnCount: 7,
    columns: ['id', 'user_id', 'title', 'message', 'is_read', 'metadata', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.user_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
  loan_applications: {
    label: 'Pengajuan Pembiayaan Syariah (Loan Applications)',
    columnCount: 15,
    columns: ['id', 'application_no', 'member_id', 'member_name', 'akad_type', 'peruntukan', 'loan_amount', 'tenor_months', 'margin_rate_pa', 'total_margin', 'total_payment', 'monthly_installment', 'status', 'committee_notes', 'created_at'],
    primaryKey: 'id',
    ddlSql: `CREATE TABLE IF NOT EXISTS public.loan_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_no VARCHAR(100) NOT NULL UNIQUE,
  member_id VARCHAR(50) NOT NULL,
  member_name VARCHAR(255) NOT NULL,
  akad_type VARCHAR(50) NOT NULL,
  peruntukan VARCHAR(100) NOT NULL,
  loan_amount NUMERIC(15,2) NOT NULL,
  tenor_months INT NOT NULL,
  margin_rate_pa NUMERIC(5,2) NOT NULL,
  total_margin NUMERIC(15,2) NOT NULL,
  total_payment NUMERIC(15,2) NOT NULL,
  monthly_installment NUMERIC(15,2) NOT NULL,
  status VARCHAR(30) DEFAULT 'SUBMITTED',
  committee_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  },
};

// Initial local seeds
const SEED_DATA: Record<SupabaseTableName, any[]> = {
  areas: [
    {
      id: 'AREA-01',
      referral_type: 'KOPERASI',
      kopwil: 'KOPWIL I - DKI JAKARTA',
      area_code: 'JKT-01',
      area_name: 'Pusat Jakarta - Menteng',
      bank_account_1: 'Bank BSI 7123456789 (a.n KOPSIM)',
      bank_account_2: 'Bank Mandiri 1230009876543',
      bank_account_3: 'BCA Syariah 0019283746',
      province: 'DKI Jakarta',
      city: 'Jakarta Pusat',
      sk_number: 'SK/01/KOPSIM/2024',
      potential: 'Pusat Keuangan & Perdagangan Komoditas',
      pic_name: 'Nunung Suhudiah, SE',
      pic_contact: '081234567890',
    },
    {
      id: 'AREA-02',
      referral_type: 'KOPERASI',
      kopwil: 'KOPWIL II - JAWA BARAT',
      area_code: 'JBR-01',
      area_name: 'Cabang Jawa Barat - Cianjur & Bandung',
      bank_account_1: 'Bank BSI 7987654321',
      bank_account_2: 'Bank Mandiri 1300012345678',
      bank_account_3: '',
      province: 'Jawa Barat',
      city: 'Cianjur',
      sk_number: 'SK/02/KOPSIM/2024',
      potential: 'Pertanian Beras Organik & Plywood',
      pic_name: 'Kang Dedi Sukamaju',
      pic_contact: '085299887766',
    },
    {
      id: 'AREA-03',
      referral_type: 'PROJECT',
      kopwil: 'KOPWIL III - JAWA TIMUR',
      area_code: 'JTM-01',
      area_name: 'Cabang Jawa Timur - Surabaya & Madura',
      bank_account_1: 'Bank Mandiri 1400055443322',
      bank_account_2: '',
      bank_account_3: '',
      province: 'Jawa Timur',
      city: 'Surabaya',
      sk_number: 'SK/03/KOPSIM/2024',
      potential: 'Industri Garam Rakyat & Cold-Chain Perikanan',
      pic_name: 'Bambang Sutrisno',
      pic_contact: '081900112233',
    },
  ],
  chart_of_accounts: [
    {
      id: 'COA-1010',
      account_code: '1010',
      account_name: 'Kas Operasional Pusat',
      account_group: 'Aset Lancar',
      financial_report: 'Neraca',
      normal_balance: 'Debit',
      tx_type: 'KAS',
      parent_code: '1000',
      is_active: true,
    },
    {
      id: 'COA-1020',
      account_code: '1020',
      account_name: 'Bank Syariah Indonesia (BSI)',
      account_group: 'Aset Lancar',
      financial_report: 'Neraca',
      normal_balance: 'Debit',
      tx_type: 'BANK',
      parent_code: '1000',
      is_active: true,
    },
    {
      id: 'COA-1030',
      account_code: '1030',
      account_name: 'Bank Mandiri Giro Operasional',
      account_group: 'Aset Lancar',
      financial_report: 'Neraca',
      normal_balance: 'Debit',
      tx_type: 'BANK',
      parent_code: '1000',
      is_active: true,
    },
    {
      id: 'COA-2010',
      account_code: '2010',
      account_name: 'Simpanan Pokok Anggota',
      account_group: 'Ekuitas / Modal Sendiri',
      financial_report: 'Neraca',
      normal_balance: 'Kredit',
      tx_type: 'SIMPANAN',
      parent_code: '2000',
      is_active: true,
    },
    {
      id: 'COA-2020',
      account_code: '2020',
      account_name: 'Simpanan Wajib Anggota',
      account_group: 'Ekuitas / Modal Sendiri',
      financial_report: 'Neraca',
      normal_balance: 'Kredit',
      tx_type: 'SIMPANAN',
      parent_code: '2000',
      is_active: true,
    },
    {
      id: 'COA-2030',
      account_code: '2030',
      account_name: 'Simpanan Sukarela / Manasuka',
      account_group: 'Liabilitas Jangka Pendek',
      financial_report: 'Neraca',
      normal_balance: 'Kredit',
      tx_type: 'SIMPANAN',
      parent_code: '2000',
      is_active: true,
    },
    {
      id: 'COA-4010',
      account_code: '4010',
      account_name: 'Pendapatan Penjualan Komoditas Riil',
      account_group: 'Pendapatan Usaha',
      financial_report: 'Laba Rugi',
      normal_balance: 'Kredit',
      tx_type: 'PROJECT',
      parent_code: '4000',
      is_active: true,
    },
    {
      id: 'COA-5010',
      account_code: '5010',
      account_name: 'Harga Pokok Penjualan (HPP) Komoditas',
      account_group: 'Beban Pokok Usaha',
      financial_report: 'Laba Rugi',
      normal_balance: 'Debit',
      tx_type: 'PROJECT',
      parent_code: '5000',
      is_active: true,
    },
  ],
  customers: [
    {
      id: 'CUST-001',
      customer_code: 'CUST-001',
      name: 'PT Boga Maritim Sejahtera',
      pic_name: 'Hendro Wijaya',
      phone: '081288990011',
      email: 'hendro@bogamaritim.co.id',
      address: 'Kawasan Industri MM2100 Blok C-4',
      province: 'Jawa Barat',
      city: 'Bekasi',
      tax_number: '01.234.567.8-412.000',
      category: 'Retail & Restoran Horeka',
      status: 'AKTIF',
      notes: 'Buyer reguler ikan tuna segar dan cumi beku',
    },
    {
      id: 'CUST-002',
      customer_code: 'CUST-002',
      name: 'Koperasi Pasar Induk Beras',
      pic_name: 'Drs. H. Mulyadi',
      phone: '081377889900',
      email: 'mulyadi.cipinang@gmail.com',
      address: 'Pasar Induk Cipinang Blok A No. 12',
      province: 'DKI Jakarta',
      city: 'Jakarta Timur',
      tax_number: '02.345.678.9-005.000',
      category: 'Distributor Pangan',
      status: 'AKTIF',
      notes: 'Distributor pasokan beras organik Cianjur',
    },
    {
      id: 'CUST-003',
      customer_code: 'CUST-003',
      name: 'CV Garam Anugerah Mandiri',
      pic_name: 'Ir. Susilo Pratama',
      phone: '081900112233',
      email: 'susilo@garamanugerah.com',
      address: 'Jl. Rungkut Industri No. 12',
      province: 'Jawa Timur',
      city: 'Surabaya',
      tax_number: '03.456.789.0-602.000',
      category: 'Industri Manufaktur',
      status: 'AKTIF',
      notes: 'Pabrik pengolahan garam halus industri',
    },
  ],
  member_registrations: [
    {
      id: 'REG-2608-001',
      submitted_at: '2026-08-20T10:15:00Z',
      full_name: 'Muhammad Farhan',
      nik: '3201011508920005',
      birth_place: 'Bogor',
      birth_date: '1992-08-15',
      gender: 'L',
      address: 'Jl. Pajajaran No. 45',
      city: 'Bogor',
      province: 'Jawa Barat',
      whatsapp: '081299887766',
      email: 'farhan.m@gmail.com',
      member_status: 'Calon Anggota',
      profession: 'Wiraswasta Agrobisnis',
      savings_type: 'Pokok (500k) + Wajib 3th (360k)',
      transfer_amount: 860000,
      transfer_date: '2026-08-20',
      transfer_proof_url: '/assets/MasterBlankoID.jpg',
      ktp_url: '',
      selfie_url: '',
      approval_status: 'APPROVED',
      verification_status: 'Telah Diverifikasi & Diterbitkan KTA',
    },
    {
      id: 'REG-2608-002',
      submitted_at: '2026-08-21T08:30:00Z',
      full_name: 'Dewi Sartika Putri',
      nik: '3171014502880002',
      birth_place: 'Jakarta',
      birth_date: '1988-02-14',
      gender: 'P',
      address: 'Jl. Cikini Raya No. 18',
      city: 'Jakarta Pusat',
      province: 'DKI Jakarta',
      whatsapp: '085711223344',
      email: 'dewi.sartika@gmail.com',
      member_status: 'Calon Anggota',
      profession: 'Konsultan Keuangan Syariah',
      savings_type: 'Pokok (500k) + Wajib (360k) + Sukarela (1jt)',
      transfer_amount: 1860000,
      transfer_date: '2026-08-21',
      transfer_proof_url: '',
      ktp_url: '',
      selfie_url: '',
      approval_status: 'PENDING',
      verification_status: 'Menunggu Konfirmasi Slip Bank',
    },
  ],
  members: [
    {
      id: '0824-03001',
      member_no: '0824-03001',
      registered_at: '2024-08-10',
      full_name: 'H. Ahmad Dahlan',
      gender: 'L',
      province: 'DKI Jakarta',
      city: 'Jakarta Pusat',
      address: 'Jl. Pegangsaan Barat No. 14, Menteng',
      occupation: 'Pengusaha Komoditas',
      username: 'ahmad.dahlan',
      birth_date: '1978-05-12',
      birth_place: 'Yogyakarta',
      area_id: 'AREA-01',
      status: 'AKTIF',
      simpanan_pokok: 500000,
      simpanan_wajib: 360000,
      simpanan_sukarela: 5000000,
      created_at: '2024-08-10T00:00:00Z',
    },
    {
      id: '0824-03002',
      member_no: '0824-03002',
      registered_at: '2024-08-11',
      full_name: 'Siti Rahmah, S.Pd',
      gender: 'P',
      province: 'Jawa Barat',
      city: 'Bandung',
      address: 'Jl. Asia Afrika No. 88',
      occupation: 'Pendidik & Wiraswasta',
      username: 'siti.rahmah',
      birth_date: '1985-09-20',
      birth_place: 'Bandung',
      area_id: 'AREA-02',
      status: 'AKTIF',
      simpanan_pokok: 500000,
      simpanan_wajib: 360000,
      simpanan_sukarela: 2000000,
      created_at: '2024-08-11T00:00:00Z',
    },
    {
      id: '0824-03003',
      member_no: '0824-03003',
      registered_at: '2024-08-12',
      full_name: 'Bambang Sutrisno',
      gender: 'L',
      province: 'Jawa Timur',
      city: 'Surabaya',
      address: 'Jl. Pemuda No. 45',
      occupation: 'Supplier Perikanan',
      username: 'bambang.s',
      birth_date: '1980-03-15',
      birth_place: 'Surabaya',
      area_id: 'AREA-03',
      status: 'AKTIF',
      simpanan_pokok: 500000,
      simpanan_wajib: 360000,
      simpanan_sukarela: 10000000,
      created_at: '2024-08-12T00:00:00Z',
    },
    {
      id: '0824-03004',
      member_no: '0824-03004',
      registered_at: '2024-08-14',
      full_name: 'Dr. Hamdan Zoelva',
      gender: 'L',
      province: 'DKI Jakarta',
      city: 'Jakarta Pusat',
      address: 'Jl. Taman Amir Hamzah No. 6A',
      occupation: 'Akademisi / Praktisi Hukum',
      username: 'hamdan.zoelva',
      birth_date: '1962-06-21',
      birth_place: 'Bima',
      area_id: 'AREA-01',
      status: 'AKTIF',
      simpanan_pokok: 500000,
      simpanan_wajib: 360000,
      simpanan_sukarela: 15000000,
      created_at: '2024-08-14T00:00:00Z',
    },
    {
      id: '0824-03005',
      member_no: '0824-03005',
      registered_at: '2024-08-15',
      full_name: 'Nunung Suhudiah, SE',
      gender: 'P',
      province: 'DKI Jakarta',
      city: 'Jakarta Selatan',
      address: 'Jl. Tebet Raya No. 20',
      occupation: 'Ekonom & Pengusaha',
      username: 'nunung.suhudiah',
      birth_date: '1975-11-10',
      birth_place: 'Jakarta',
      area_id: 'AREA-01',
      status: 'AKTIF',
      simpanan_pokok: 500000,
      simpanan_wajib: 360000,
      simpanan_sukarela: 10000000,
      created_at: '2024-08-15T00:00:00Z',
    },
  ],
  products: [
    {
      id: 'PRD-IKAN-01',
      sku_code: 'SKU-TUNA-01',
      sku_name: 'Ikan Tuna Segar Tangkap Laut (Yellowfin)',
      group_id: 'GRP-IKAN',
      group_name: 'TRADING IKAN',
      subgroup: 'Ikan Laut Segar',
      brand: 'Kopsim Bahari',
      grade: 'Grade A Sashimi',
      packaging: 'Sterofoam + Ice Pack 25kg',
      availability: 'Tersedia',
      moq: 25,
      supply_capacity: '20 Ton / Bulan',
    },
    {
      id: 'PRD-IKAN-02',
      sku_code: 'SKU-LAYANG-01',
      sku_name: 'Ikan Layang Tangkap Segar',
      group_id: 'GRP-IKAN',
      group_name: 'TRADING IKAN',
      subgroup: 'Ikan Laut Segar',
      brand: 'Kopsim Bahari',
      grade: 'Grade A',
      packaging: 'Keranjang 30kg',
      availability: 'Tersedia',
      moq: 30,
      supply_capacity: '15 Ton / Bulan',
    },
    {
      id: 'PRD-MEAT-01',
      sku_code: 'SKU-MEAT-01',
      sku_name: 'Daging Sapi Prime Cut Halal Segar',
      group_id: 'GRP-MEAT',
      group_name: 'DISTRIBUTOR MEATSHOP',
      subgroup: 'Daging Sapi Segar',
      brand: 'Kopsim Meatshop',
      grade: 'Prime Halal',
      packaging: 'Vacuum Pack 1kg',
      availability: 'Tersedia',
      moq: 10,
      supply_capacity: '30 Ton / Bulan',
    },
    {
      id: 'PRD-MEAT-02',
      sku_code: 'SKU-AYAM-01',
      sku_name: 'Daging Ayam Karkas Broiler Segar',
      group_id: 'GRP-MEAT',
      group_name: 'DISTRIBUTOR MEATSHOP',
      subgroup: 'Unggas Segar',
      brand: 'Kopsim Meatshop',
      grade: 'Broiler Super',
      packaging: 'Plastik Higienis 1kg',
      availability: 'Tersedia',
      moq: 20,
      supply_capacity: '25 Ton / Bulan',
    },
    {
      id: 'PRD-AGRI-01',
      sku_code: 'SKU-BERAS-01',
      sku_name: 'Beras Organik Pandan Wangi Cianjur',
      group_id: 'GRP-AGRI',
      group_name: 'PERTANIAN',
      subgroup: 'Beras & Padi',
      brand: 'Kopsim Agri',
      grade: 'Premium SVLK',
      packaging: 'Karung Vakum 25kg / 50kg',
      availability: 'Tersedia',
      moq: 100,
      supply_capacity: '50 Ton / Bulan',
    },
    {
      id: 'PRD-GARAM-01',
      sku_code: 'SKU-GARAM-01',
      sku_name: 'Garam Kristal NaCl > 97% Food Grade',
      group_id: 'GRP-GARAM',
      group_name: 'GARAM',
      subgroup: 'Garam Industri',
      brand: 'Kopsim Garamindo',
      grade: 'Grade K1',
      packaging: 'Woven Bag 50kg',
      availability: 'Tersedia',
      moq: 1000,
      supply_capacity: '100 Ton / Bulan',
    },
    {
      id: 'PRD-MINYAK-01',
      sku_code: 'SKU-RPO-01',
      sku_name: 'Minyak Makan Merah (Red Palm Oil)',
      group_id: 'GRP-MINYAK',
      group_name: 'MINYAK MERAH',
      subgroup: 'Bio Industri & Nutrisi',
      brand: 'Kopsim Nabati',
      grade: 'Virgin Unrefined',
      packaging: 'Jerigen Food Grade 20L / Drum 200L',
      availability: 'Tersedia',
      moq: 20,
      supply_capacity: '30 Ton / Bulan',
    },
    {
      id: 'PRD-PLY-01',
      sku_code: 'SKU-PLY-01',
      sku_name: 'Kayu Lapis Plywood Grade Ekspor 18mm',
      group_id: 'GRP-PLYWOOD',
      group_name: 'PLYWOOD',
      subgroup: 'Plywood Ekspor',
      brand: 'Kopsim Wood',
      grade: 'BB/CC Export',
      packaging: 'Pallet 50 Lembar',
      availability: 'Tersedia',
      moq: 50,
      supply_capacity: '5000 Lembar / Bulan',
    },
    {
      id: 'PRD-MBG-01',
      sku_code: 'SKU-MBG-01',
      sku_name: 'Paket Pangan Makan Bergizi Gratis (MBG)',
      group_id: 'GRP-MBG',
      group_name: 'SUPPLIER MBG',
      subgroup: 'Paket Siap Saji',
      brand: 'MBG Mandiri',
      grade: 'Standar Gizi Nasional',
      packaging: 'Bento Box Higienis',
      availability: 'Tersedia',
      moq: 50,
      supply_capacity: '10.000 Porsi / Hari',
    },
    {
      id: 'PRD-HAJI-01',
      sku_code: 'SKU-HAJI-01',
      sku_name: 'Paket Investasi Sarana Kampung Haji',
      group_id: 'GRP-HAJI',
      group_name: 'KAMPUNG HAJI',
      subgroup: 'Investasi Aset',
      brand: 'Kampung Haji Syariah',
      grade: 'Syariah Aset',
      packaging: 'Sertifikat Portofolio',
      availability: 'Tersedia',
      moq: 1,
      supply_capacity: '100 Unit',
    },
  ],
  role_permissions: [
    {
      id: 'ROLE-ADMIN',
      role_name: 'ADMIN',
      permissions: ['read_all', 'write_all', 'delete_all', 'manage_users', 'export_financials', 'audit_database'],
    },
    {
      id: 'ROLE-DIRECTOR',
      role_name: 'DIRECTOR',
      permissions: ['read_all', 'write_transactions', 'view_reports', 'approve_registrations', 'view_projects'],
    },
    {
      id: 'ROLE-ANGGOTA',
      role_name: 'ANGGOTA',
      permissions: ['view_profile', 'view_simpanan', 'download_kta', 'view_portfolio', 'submit_inquiry'],
    },
  ],
  suppliers: [
    {
      id: 'SUPP-001',
      supplier_code: 'SUPP-001',
      name: 'Kelompok Nelayan Mandiri Pesisir',
      pic_name: 'Pak Samsul',
      phone: '082144556677',
      email: 'nelayan.muarabaru@gmail.com',
      address: 'Dermaga Muara Baru Dermaga 03',
      province: 'DKI Jakarta',
      city: 'Jakarta Utara',
      tax_number: '04.567.890.1-008.000',
      category: 'Hasil Laut Tangkap',
      status: 'AKTIF',
      notes: 'Pemasok tuna, cumi, dan kakap merah segar',
    },
    {
      id: 'SUPP-002',
      supplier_code: 'SUPP-002',
      name: 'Gabungan Kelompok Tani Subur Makmur',
      pic_name: 'Kang Dedi',
      phone: '085299887766',
      email: 'gapoktan.sukamaju@gmail.com',
      address: 'Desa Sukamaju Kec. Pacet',
      province: 'Jawa Barat',
      city: 'Cianjur',
      tax_number: '05.678.901.2-406.000',
      category: 'Pertanian Padi & Jagung',
      status: 'AKTIF',
      notes: 'Petani mitra beras organik binaan KOPSIM',
    },
    {
      id: 'SUPP-003',
      supplier_code: 'SUPP-003',
      name: 'Koperasi Tambak Garam Rakyat',
      pic_name: 'H. Ridwan',
      phone: '087811223344',
      email: 'tambak.indramayu@gmail.com',
      address: 'Pesisir Pantura Losarang',
      province: 'Jawa Barat',
      city: 'Indramayu',
      tax_number: '06.789.012.3-437.000',
      category: 'Garam Bahan Baku',
      status: 'AKTIF',
      notes: 'Kelompok petambak garam evaporasi matahari',
    },
  ],
  transactions: [
    {
      id: 'T260815001',
      transaction_no: 'T260815001',
      transaction_date: '2026-08-15',
      referral_type: 'KOPERASI',
      area_name: 'PUSAT JAKARTA',
      transaction_type: 'MASUK',
      payment_method: 'Bank BSI',
      amount: 5000000,
      file_url: '',
      account_name_legacy: 'Bank BSI',
      description: 'Penerimaan Simpanan Pokok 10 Anggota Baru',
      category_name: 'Simpanan Pokok',
      product_name: '',
      supplier_name: '',
      customer_name: '',
      qty: 1,
      price: 5000000,
      created_at: '2026-08-15T10:30:00Z',
      updated_at: '2026-08-15T10:30:00Z',
    },
    {
      id: 'T260816002',
      transaction_no: 'T260816002',
      transaction_date: '2026-08-16',
      referral_type: 'KOPERASI',
      area_name: 'PUSAT JAKARTA',
      transaction_type: 'MASUK',
      payment_method: 'Bank BSI',
      amount: 3600000,
      file_url: '',
      account_name_legacy: 'Bank BSI',
      description: 'Setoran Simpanan Wajib 3 Tahun',
      category_name: 'Simpanan Wajib',
      product_name: '',
      supplier_name: '',
      customer_name: '',
      qty: 1,
      price: 3600000,
      created_at: '2026-08-16T11:15:00Z',
      updated_at: '2026-08-16T11:15:00Z',
    },
    {
      id: 'P260817001',
      transaction_no: 'P260817001',
      transaction_date: '2026-08-17',
      referral_type: 'PROJECT',
      area_name: 'TRADING IKAN',
      transaction_type: 'MASUK',
      payment_method: 'Bank Mandiri',
      amount: 32500000,
      file_url: '',
      account_name_legacy: 'DANA PROJECT',
      description: 'Penjualan ke Mitra Restoran Cold-Chain',
      category_name: 'Penjualan Komoditas',
      product_name: 'Ikan Tuna Segar Grade A',
      supplier_name: '',
      customer_name: 'CUST-001',
      qty: 500,
      price: 65000,
      created_at: '2026-08-17T09:20:00Z',
      updated_at: '2026-08-17T09:20:00Z',
    },
  ],
  user_roles: [
    {
      id: 'UR-01',
      user_id: 'admin@kopsim.id',
      role: 'ADMIN',
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'UR-02',
      user_id: 'director@kopsim.id',
      role: 'DIRECTOR',
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'UR-03',
      user_id: 'anggota@kopsim.id',
      role: 'ANGGOTA',
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
  transaction_categories: [
    {
      id: 1,
      type: 'SIMPANAN',
      category_code: 'SIMP_POKOK',
      name: 'Simpanan Pokok',
      account_code: '2010',
      account_name: 'Simpanan Pokok Anggota',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 2,
      type: 'SIMPANAN',
      category_code: 'SIMP_WAJIB',
      name: 'Simpanan Wajib',
      account_code: '2020',
      account_name: 'Simpanan Wajib Anggota',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 3,
      type: 'SIMPANAN',
      category_code: 'SIMP_SUKARELA',
      name: 'Simpanan Sukarela',
      account_code: '2030',
      account_name: 'Simpanan Sukarela / Manasuka',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 4,
      type: 'PINJAMAN',
      category_code: 'PINJ_ANGSURAN',
      name: 'Angsuran Pinjaman',
      account_code: '113.01',
      account_name: 'Piutang Pinjaman Anggota',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 5,
      type: 'PROJECT',
      category_code: 'KOMODITAS_IKAN',
      name: 'Trading Ikan Tuna & Hasil Laut',
      account_code: '4010',
      account_name: 'Pendapatan Penjualan Komoditas Riil',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 6,
      type: 'PROJECT',
      category_code: 'KOMODITAS_BERAS',
      name: 'Trading Beras Organik Pandan Wangi',
      account_code: '4010',
      account_name: 'Pendapatan Penjualan Komoditas Riil',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 7,
      type: 'PROJECT',
      category_code: 'KOMODITAS_GARAM',
      name: 'Trading Garam Industri & Pangan',
      account_code: '4010',
      account_name: 'Pendapatan Penjualan Komoditas Riil',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  news_articles: [
    {
      id: 'news-001',
      kategori: 'kemitraan',
      project_id: null,
      judul: 'Kemitraan Strategis KOPSIM Mandiri Perkuat Rantai Pasok Pangan',
      ringkasan: 'KOPSIM Mandiri memperluas kemitraan strategis perikanan dan pertanian nasional.',
      konten: 'Ekspansi kemitraan rantai pasok pangan dan perikanan terpadu.',
      lokasi: 'Jakarta Pusat',
      foto_url: '/assets/portfolio/perikanan-ikan-layang-ambon.jpg',
      tanggal: '2026-08-25',
      dibuat_oleh: null,
      status: 'terbit',
      created_at: '2026-08-25T10:00:00Z',
    },
  ],
  project_updates: [
    {
      id: 'upd-001',
      project_id: 'perikanan-ambon',
      judul: 'Pengiriman 25 Ton Ikan Layang Beku dari Ambon ke Surabaya',
      narasi: 'Cold storage beroperasi optimal menyalurkan hasil tangkap nelayan Maluku.',
      foto_url: '/assets/portfolio/perikanan-ikan-layang-ambon.jpg',
      tanggal: '2026-08-22',
      created_at: '2026-08-22T08:00:00Z',
    },
  ],
  profiles: [
    {
      id: 'prof-001',
      full_name: 'Administrator KOPSIM',
      role: 'ADMIN',
      phone: '081234567890',
      avatar_url: '',
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
  roles: [
    {
      id: 'role-001',
      name: 'ADMIN',
      description: 'Akses penuh seluruh modul sistem',
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'role-002',
      name: 'DIRECTOR',
      description: 'Akses laporan keuangan, approval, dan monitoring',
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'role-003',
      name: 'ANGGOTA',
      description: 'Akses portal anggota, KTA digital, dan simpanan',
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
  audit_logs: [
    {
      id: 'audit-001',
      user_id: null,
      user_email: 'admin@kopsim.id',
      action: 'SYSTEM_BOOTSTRAP',
      entity: 'database_schema',
      entity_id: 'init_v1',
      old_values: null,
      new_values: { status: 'schema_validated' },
      ip_address: '127.0.0.1',
      created_at: '2026-08-26T00:00:00Z',
    },
  ],
  payment_requests: [
    {
      id: 'pay-seed-1',
      order_id: 'INV-KOPSIM-202608-001',
      idempotency_key: 'idemp-seed-1',
      member_id: '0824-03001',
      member_name: 'M. FACHRI MUBAROK',
      amount: 500000,
      fee: 0,
      total_amount: 500000,
      payment_type: 'QRIS',
      payment_channel: 'QRIS_DYNAMIC',
      status: 'POSTED',
      expiry_time: '2026-08-28T09:00:00Z',
      paid_at: '2026-08-28T08:15:00Z',
      posted_transaction_id: 'TRX-PG-20260828-001',
      webhook_attempts: 1,
      created_at: '2026-08-28T08:00:00Z',
    },
  ],
  notification_jobs: [
    {
      id: 'job-seed-1',
      type: 'PAYMENT_POSTED',
      recipient: '+6281234567890',
      recipient_name: 'M. FACHRI MUBAROK',
      channel: 'WHATSAPP',
      provider: 'FONNTE',
      payload: { title: 'Setoran Simpanan Sukses', amount: 500000 },
      status: 'SENT',
      attempts: 1,
      max_attempts: 3,
      idempotency_key: 'notif-idemp-seed-1',
      sent_at: '2026-08-28T08:16:00Z',
      created_at: '2026-08-28T08:15:00Z',
    },
  ],
  user_notifications: [
    {
      id: 'unotif-seed-1',
      user_id: '0824-03001',
      title: 'Setoran Simpanan Wajib Diterima',
      message: 'Setoran via QRIS sebesar Rp 500.000 telah diverifikasi.',
      is_read: false,
      metadata: { order_id: 'INV-KOPSIM-202608-001' },
      created_at: '2026-08-28T08:16:00Z',
    },
  ],
  loan_applications: [
    {
      id: 'app-seed-1',
      application_no: 'PB-202608-001',
      member_id: '0824-03001',
      member_name: 'M. FACHRI MUBAROK',
      akad_type: 'MURABAHAH',
      peruntukan: 'MODAL_KERJA_PERTANIAN',
      loan_amount: 15000000,
      tenor_months: 12,
      margin_rate_pa: 6.0,
      total_margin: 900000,
      total_payment: 1590000,
      monthly_installment: 1325000,
      status: 'SUBMITTED',
      committee_notes: 'Menunggu review komite pembiayaan.',
      created_at: '2026-08-28T10:00:00Z',
    },
  ],
};

export const masterDataService = {
  getLocalStorageKey(table: SupabaseTableName): string {
    return `KOPSIM_TABLE_${table.toUpperCase()}`;
  },

  getStoredData<T = any>(table: SupabaseTableName): T[] {
    try {
      const stored = localStorage.getItem(this.getLocalStorageKey(table));
      if (stored) return JSON.parse(stored);
    } catch {
      // fallback
    }
    const seed = SEED_DATA[table] || [];
    localStorage.setItem(this.getLocalStorageKey(table), JSON.stringify(seed));
    return seed as T[];
  },

  saveStoredData<T = any>(table: SupabaseTableName, data: T[]): void {
    localStorage.setItem(this.getLocalStorageKey(table), JSON.stringify(data));
  },

  /**
   * Audit all tables in Supabase with exact live checks
   */
  async auditAllTables(): Promise<TableAuditInfo[]> {
    const tableKeys: SupabaseTableName[] = [
      'areas',
      'transaction_categories',
      'chart_of_accounts',
      'customers',
      'member_registrations',
      'members',
      'products',
      'role_permissions',
      'suppliers',
      'transactions',
      'user_roles',
    ];

    const results: TableAuditInfo[] = [];

    for (const tbl of tableKeys) {
      const meta = SUPABASE_TABLES_METADATA[tbl];
      const startTime = performance.now();

      if (!isSupabaseConfigured) {
        const localData = this.getStoredData(tbl);
        results.push({
          tableName: tbl,
          label: meta.label,
          columnCount: meta.columnCount,
          columnsList: meta.columns,
          isConfigured: false,
          isConnected: false,
          rowCount: localData.length,
          latencyMs: 0,
          statusMessage: 'Supabase URL/Key belum dikonfigurasi (Menggunakan data lokal).',
          lastChecked: new Date().toLocaleTimeString('id-ID'),
        });
        continue;
      }

      const client = getSupabaseClient();
      if (!client) {
        results.push({
          tableName: tbl,
          label: meta.label,
          columnCount: meta.columnCount,
          columnsList: meta.columns,
          isConfigured: true,
          isConnected: false,
          rowCount: 0,
          latencyMs: 0,
          statusMessage: 'Client Supabase gagal diinisialisasi.',
          lastChecked: new Date().toLocaleTimeString('id-ID'),
        });
        continue;
      }

      try {
        const { count, error } = await client
          .from(tbl)
          .select('*', { count: 'exact', head: true });

        const latencyMs = Math.round(performance.now() - startTime);

        if (error) {
          const localData = this.getStoredData(tbl);
          results.push({
            tableName: tbl,
            label: meta.label,
            columnCount: meta.columnCount,
            columnsList: meta.columns,
            isConfigured: true,
            isConnected: false,
            rowCount: localData.length,
            latencyMs,
            statusMessage: `Tabel belum dibuat / RLS error: ${error.message}`,
            lastChecked: new Date().toLocaleTimeString('id-ID'),
          });
        } else {
          results.push({
            tableName: tbl,
            label: meta.label,
            columnCount: meta.columnCount,
            columnsList: meta.columns,
            isConfigured: true,
            isConnected: true,
            rowCount: count ?? 0,
            latencyMs,
            statusMessage: `Tersambung aktif (${count ?? 0} baris data).`,
            lastChecked: new Date().toLocaleTimeString('id-ID'),
          });
        }
      } catch (err: any) {
        const latencyMs = Math.round(performance.now() - startTime);
        results.push({
          tableName: tbl,
          label: meta.label,
          columnCount: meta.columnCount,
          columnsList: meta.columns,
          isConfigured: true,
          isConnected: false,
          rowCount: 0,
          latencyMs,
          statusMessage: `Kesalahan koneksi: ${err?.message || err}`,
          lastChecked: new Date().toLocaleTimeString('id-ID'),
        });
      }
    }

    return results;
  },

  /**
   * Fetch records for any of the master tables
   */
  async getTableRecords<T = any>(table: SupabaseTableName): Promise<{ data: T[]; source: 'SUPABASE' | 'LOCAL' }> {
    const client = getSupabaseClient();
    if (client) {
      try {
        const { data, error } = await client.from(table).select('*');
        if (!error && data && data.length > 0) {
          this.saveStoredData(table, data);
          return { data: data as T[], source: 'SUPABASE' };
        }
      } catch (err) {
        console.warn(`Supabase getTableRecords (${table}) fallback:`, err);
      }
    }

    return { data: this.getStoredData(table) as T[], source: 'LOCAL' };
  },

  /**
   * Create or Update a record in any of the master tables
   */
  async saveRecord<T extends { id?: any; area_code?: string; category_code?: string }>(
    table: SupabaseTableName,
    record: T
  ): Promise<{ success: boolean; id: string; error?: string; source: 'SUPABASE' | 'LOCAL' }> {
    const records = this.getStoredData(table) as any[];
    const recId = record.id !== undefined && record.id !== null ? String(record.id) : '';
    const existingIndex = records.findIndex((r) => {
      if (recId && String(r.id) === recId) return true;
      if (table === 'areas' && record.area_code && r.area_code === record.area_code) return true;
      if (table === 'transaction_categories' && record.category_code && r.category_code === record.category_code) return true;
      return false;
    });
    const isEdit = existingIndex !== -1;

    if (isEdit) {
      records[existingIndex] = { ...records[existingIndex], ...record };
    } else {
      records.unshift(record);
    }
    this.saveStoredData(table, records);

    const client = getSupabaseClient();
    let savedToSupabase = false;

    if (client) {
      try {
        // Clean payload for tables with bigint identity (areas, transaction_categories)
        const payload: any = { ...record };
        if ((table === 'areas' || table === 'transaction_categories') && typeof payload.id === 'string' && isNaN(Number(payload.id))) {
          delete payload.id; // Let Postgres sequence assign id
        }

        if (isEdit) {
          let query = client.from(table).update(payload);
          if (recId && !isNaN(Number(recId))) {
            query = query.eq('id', Number(recId));
          } else if (recId && table !== 'areas' && table !== 'transaction_categories') {
            query = query.eq('id', recId);
          } else if (table === 'areas' && record.area_code) {
            query = query.eq('area_code', record.area_code);
          } else if (table === 'transaction_categories' && record.category_code) {
            query = query.eq('category_code', record.category_code);
          } else {
            query = query.eq('id', recId);
          }
          const { error } = await query;
          if (!error) savedToSupabase = true;
        } else {
          const { error } = await client.from(table).insert([payload]);
          if (!error) savedToSupabase = true;
        }
      } catch (err) {
        console.warn(`Supabase saveRecord (${table}) fallback:`, err);
      }
    }

    return {
      success: true,
      id: recId || (record as any).area_code || (record as any).category_code || 'NEW',
      source: savedToSupabase ? 'SUPABASE' : 'LOCAL',
    };
  },

  /**
   * Delete a record from any of the master tables
   */
  async deleteRecord(table: SupabaseTableName, id: string): Promise<{ success: boolean; error?: string }> {
    let records = this.getStoredData(table);
    records = records.filter((r) => String(r.id) !== String(id) && (r.area_code !== id) && (r.category_code !== id));
    this.saveStoredData(table, records);

    const client = getSupabaseClient();
    if (client) {
      try {
        if (!isNaN(Number(id))) {
          await client.from(table).delete().eq('id', Number(id));
        } else if (table === 'areas') {
          await client.from(table).delete().eq('area_code', id);
        } else if (table === 'transaction_categories') {
          await client.from(table).delete().eq('category_code', id);
        } else {
          await client.from(table).delete().eq('id', id);
        }
      } catch (err) {
        console.warn(`Supabase deleteRecord (${table}) fallback:`, err);
      }
    }

    return { success: true };
  },

  /**
   * Push Seed Data into Supabase
   */
  async seedTableToSupabase(table: SupabaseTableName): Promise<{ success: boolean; count: number; error?: string }> {
    const client = getSupabaseClient();
    if (!client) {
      return { success: false, count: 0, error: 'Supabase client belum terhubung' };
    }

    const rawData = this.getStoredData(table);
    const data = rawData.map((item) => {
      const cleanItem: any = { ...item };
      if ((table === 'areas' || table === 'transaction_categories') && typeof cleanItem.id === 'string' && isNaN(Number(cleanItem.id))) {
        delete cleanItem.id;
      }
      return cleanItem;
    });

    const conflictTarget =
      table === 'areas'
        ? 'area_code'
        : table === 'transaction_categories'
        ? 'category_code'
        : 'id';

    try {
      const { error } = await client.from(table).upsert(data, { onConflict: conflictTarget });
      if (error) {
        return { success: false, count: 0, error: error.message };
      }
      return { success: true, count: data.length };
    } catch (err: any) {
      return { success: false, count: 0, error: err?.message || String(err) };
    }
  },

  /**
   * Generate Full DDL Script for all master tables
   */
  getAllTablesDdlSql(): string {
    return `-- ====================================================================
-- KOPSIM MANDIRI: MASTER DATABASE DDL (11 TABEL RESMI)
-- ====================================================================

${Object.values(SUPABASE_TABLES_METADATA)
  .map((m) => m.ddlSql)
  .join('\n\n')}
`;
  },
};
