-- ==============================================================================
-- KOPSIM MANDIRI: MASTER DATABASE MIGRATION & DOMAIN SCHEMA
-- Migration: 20260826000001_core_schema_and_domains.sql
-- Description: Core schema, domain contracts, foreign keys, uniqueness, and constraints
-- ==============================================================================

-- 1. Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- DOMAIN 1: MASTER REFERENSI & ORGANISASI (Areas, COA, Categories)
-- ==============================================================================

-- Tabel Master Wilayah / Cabang (public.areas)
CREATE TABLE IF NOT EXISTS public.areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referral_type VARCHAR(30) NOT NULL DEFAULT 'KOPERASI',
  kopwil VARCHAR(100) DEFAULT '',
  area_code VARCHAR(50) NOT NULL UNIQUE,
  area_name VARCHAR(255) NOT NULL,
  bank_account_1 TEXT DEFAULT '',
  bank_account_2 TEXT DEFAULT '',
  bank_account_3 TEXT DEFAULT '',
  province VARCHAR(100) DEFAULT 'DKI Jakarta',
  city VARCHAR(150) DEFAULT 'Jakarta Pusat',
  sk_number VARCHAR(150) DEFAULT '',
  potential TEXT DEFAULT '',
  pic_name VARCHAR(150) DEFAULT '',
  pic_contact VARCHAR(100) DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Master Bagan Akun / Chart of Accounts (public.chart_of_accounts)
CREATE TABLE IF NOT EXISTS public.chart_of_accounts (
  id VARCHAR(50) PRIMARY KEY,
  account_code VARCHAR(50) NOT NULL UNIQUE,
  account_name VARCHAR(255) NOT NULL,
  account_group VARCHAR(100) NOT NULL,
  financial_report VARCHAR(100) NOT NULL,
  normal_balance VARCHAR(10) NOT NULL CHECK (normal_balance IN ('Debit', 'Kredit')),
  tx_type VARCHAR(50) DEFAULT 'UMUM',
  parent_code VARCHAR(50) DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Master Kategori Transaksi (public.transaction_categories)
CREATE TABLE IF NOT EXISTS public.transaction_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(20) NOT NULL CHECK (type IN ('SIMPANAN', 'PINJAMAN', 'PROJECT', 'OPERASIONAL', 'LAINNYA')),
  category_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  account_code VARCHAR(50) REFERENCES public.chart_of_accounts(account_code) ON DELETE SET NULL,
  account_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- DOMAIN 2: MITRA SEKTOR RIIL (Pelanggan, Pemasok, Produk)
-- ==============================================================================

-- Tabel Master Pelanggan / Buyer (public.customers)
CREATE TABLE IF NOT EXISTS public.customers (
  id VARCHAR(50) PRIMARY KEY,
  customer_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  pic_name VARCHAR(150) DEFAULT '',
  phone VARCHAR(50) DEFAULT '',
  email VARCHAR(150) DEFAULT '',
  address TEXT DEFAULT '',
  province VARCHAR(100) DEFAULT 'DKI Jakarta',
  city VARCHAR(100) DEFAULT 'Jakarta',
  tax_number VARCHAR(50) DEFAULT '',
  category VARCHAR(100) DEFAULT 'Retail',
  status VARCHAR(20) NOT NULL DEFAULT 'AKTIF' CHECK (status IN ('AKTIF', 'NONAKTIF')),
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Master Pemasok / Nelayan / Petani (public.suppliers)
CREATE TABLE IF NOT EXISTS public.suppliers (
  id VARCHAR(50) PRIMARY KEY,
  supplier_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  pic_name VARCHAR(150) DEFAULT '',
  phone VARCHAR(50) DEFAULT '',
  email VARCHAR(150) DEFAULT '',
  address TEXT DEFAULT '',
  province VARCHAR(100) DEFAULT 'DKI Jakarta',
  city VARCHAR(100) DEFAULT 'Jakarta',
  tax_number VARCHAR(50) DEFAULT '',
  category VARCHAR(100) DEFAULT 'Hasil Laut',
  status VARCHAR(20) NOT NULL DEFAULT 'AKTIF' CHECK (status IN ('AKTIF', 'NONAKTIF')),
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Master Komoditas & SKU Produk (public.products)
CREATE TABLE IF NOT EXISTS public.products (
  id VARCHAR(50) PRIMARY KEY,
  sku_code VARCHAR(50) NOT NULL UNIQUE,
  sku_name VARCHAR(255) NOT NULL,
  group_id VARCHAR(50) DEFAULT '',
  group_name VARCHAR(100) DEFAULT '',
  subgroup VARCHAR(100) DEFAULT '',
  brand VARCHAR(100) DEFAULT '',
  grade VARCHAR(50) DEFAULT 'Grade A',
  packaging VARCHAR(100) DEFAULT 'Standard',
  availability VARCHAR(50) DEFAULT 'Tersedia',
  moq INT DEFAULT 1 CHECK (moq >= 0),
  supply_capacity VARCHAR(100) DEFAULT '10 Ton/Bulan',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- DOMAIN 3: KEANGGOTAAN (Members & Registrations)
-- ==============================================================================

-- Tabel Anggota Koperasi (public.members)
CREATE TABLE IF NOT EXISTS public.members (
  id VARCHAR(50) PRIMARY KEY,
  member_no VARCHAR(50) NOT NULL UNIQUE,
  registered_at DATE NOT NULL DEFAULT CURRENT_DATE,
  full_name VARCHAR(255) NOT NULL,
  gender VARCHAR(10) NOT NULL DEFAULT 'L' CHECK (gender IN ('L', 'P')),
  province VARCHAR(100) DEFAULT 'DKI Jakarta',
  city VARCHAR(100) DEFAULT 'Jakarta Pusat',
  address TEXT DEFAULT '',
  occupation VARCHAR(150) DEFAULT 'Anggota',
  username VARCHAR(100) UNIQUE,
  birth_date DATE DEFAULT '1990-01-01',
  birth_place VARCHAR(100) DEFAULT 'Jakarta',
  nik VARCHAR(16) NOT NULL UNIQUE CHECK (nik ~ '^[0-9]{16}$'),
  work_area VARCHAR(50) NOT NULL DEFAULT 'JKT-01',
  legacy_password_hash TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'AKTIF' CHECK (status IN ('AKTIF', 'NONAKTIF', 'PENDING', 'SUSPENDED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Pendaftaran Anggota Baru (public.member_registrations)
CREATE TABLE IF NOT EXISTS public.member_registrations (
  id VARCHAR(50) PRIMARY KEY,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  full_name VARCHAR(255) NOT NULL,
  nik VARCHAR(16) NOT NULL CHECK (nik ~ '^[0-9]{16}$'),
  birth_place VARCHAR(100) DEFAULT '',
  birth_date DATE DEFAULT '1990-01-01',
  gender VARCHAR(10) DEFAULT 'L' CHECK (gender IN ('L', 'P')),
  address TEXT DEFAULT '',
  city VARCHAR(100) DEFAULT 'Jakarta',
  province VARCHAR(100) DEFAULT 'DKI Jakarta',
  whatsapp VARCHAR(50) NOT NULL,
  email VARCHAR(150) DEFAULT '',
  member_status VARCHAR(50) DEFAULT 'Calon Anggota',
  profession VARCHAR(100) DEFAULT 'Wiraswasta',
  savings_type VARCHAR(100) DEFAULT 'Pokok + Wajib',
  transfer_amount NUMERIC(15,2) NOT NULL DEFAULT 860000.00 CHECK (transfer_amount >= 0),
  transfer_date DATE DEFAULT CURRENT_DATE,
  transfer_proof_url TEXT DEFAULT '',
  ktp_url TEXT DEFAULT '',
  selfie_url TEXT DEFAULT '',
  approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
  verification_status VARCHAR(100) DEFAULT 'Menunggu Verifikasi Admin',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- DOMAIN 4: TRANSAKSI & JURNAL KEUANGAN (Transactions)
-- ==============================================================================

-- Tabel Jurnal Transaksi Operasional & Simpanan (public.transactions)
CREATE TABLE IF NOT EXISTS public.transactions (
  id VARCHAR(50) PRIMARY KEY,
  transaction_no VARCHAR(50) NOT NULL UNIQUE,
  transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
  referral_type VARCHAR(20) NOT NULL DEFAULT 'KOPERASI' CHECK (referral_type IN ('KOPERASI', 'PROJECT')),
  area_name VARCHAR(100) NOT NULL DEFAULT 'PUSAT JAKARTA',
  transaction_type VARCHAR(10) NOT NULL CHECK (transaction_type IN ('MASUK', 'KELUAR')),
  payment_method VARCHAR(100) NOT NULL DEFAULT 'Bank BSI',
  amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0),
  file_url TEXT DEFAULT '',
  account_name_legacy VARCHAR(100) DEFAULT 'Bank BSI',
  description TEXT DEFAULT '',
  category_name VARCHAR(100) DEFAULT 'Kas',
  product_name VARCHAR(255) DEFAULT '',
  supplier_name VARCHAR(255) DEFAULT '',
  customer_name VARCHAR(255) DEFAULT '',
  qty NUMERIC(12, 2) DEFAULT 1.00 CHECK (qty >= 0),
  price NUMERIC(15, 2) DEFAULT 0.00 CHECK (price >= 0),
  member_id VARCHAR(50) REFERENCES public.members(id) ON DELETE SET NULL,
  category_code VARCHAR(50) REFERENCES public.transaction_categories(category_code) ON DELETE SET NULL,
  account_code VARCHAR(50) REFERENCES public.chart_of_accounts(account_code) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- DOMAIN 5: PROYEK & KONTEN WARTA (Project Updates & News)
-- ==============================================================================

-- Tabel Log Update Proyek Sektor Riil (public.project_updates)
CREATE TABLE IF NOT EXISTS public.project_updates (
  id VARCHAR(50) PRIMARY KEY,
  project_id VARCHAR(50) NOT NULL,
  judul VARCHAR(255) NOT NULL,
  narasi TEXT NOT NULL,
  foto_url TEXT,
  tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
  dibuat_oleh UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Kanal Berita & Publikasi (public.news_articles)
CREATE TABLE IF NOT EXISTS public.news_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kategori VARCHAR(50) NOT NULL CHECK (kategori IN ('kemitraan', 'program', 'dampak', 'update_proyek')),
  project_id VARCHAR(50),
  judul VARCHAR(255) NOT NULL,
  ringkasan TEXT NOT NULL,
  konten TEXT NOT NULL,
  lokasi VARCHAR(150),
  foto_url TEXT,
  tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
  dibuat_oleh UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'terbit')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- DOMAIN 6: IDENTITAS, RBAC & AUDIT LOGS (Profiles, Roles, Permissions, Logs)
-- ==============================================================================

-- Tabel Profil Pengguna Internal (public.profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'ANGGOTA' CHECK (role IN ('ADMIN', 'DIRECTOR', 'ANGGOTA')),
  phone VARCHAR(50),
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Master Role (public.roles)
CREATE TABLE IF NOT EXISTS public.roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Pemetaan Peran Pengguna (public.user_roles)
CREATE TABLE IF NOT EXISTS public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id UUID REFERENCES public.roles(id) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL DEFAULT 'ANGGOTA' CHECK (role IN ('ADMIN', 'DIRECTOR', 'ANGGOTA')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Hak Akses Modul (public.role_permissions)
CREATE TABLE IF NOT EXISTS public.role_permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role_name VARCHAR(50) NOT NULL UNIQUE,
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabel Audit Jejak Aktivitas (public.audit_logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_email VARCHAR(150),
  action VARCHAR(100) NOT NULL,
  entity VARCHAR(100) NOT NULL,
  entity_id VARCHAR(100),
  old_values JSONB,
  new_values JSONB,
  ip_address VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- INDEXING UNTUK QUERY OPTIMIZATION
-- ==============================================================================

-- Index Keanggotaan
CREATE INDEX IF NOT EXISTS idx_members_nik ON public.members (nik);
CREATE INDEX IF NOT EXISTS idx_members_member_no ON public.members (member_no);
CREATE INDEX IF NOT EXISTS idx_members_username ON public.members (username);
CREATE INDEX IF NOT EXISTS idx_members_work_area ON public.members (work_area);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members (status);

-- Index Transaksi
CREATE INDEX IF NOT EXISTS idx_transactions_trx_no ON public.transactions (transaction_no);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions (transaction_date DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_member_id ON public.transactions (member_id);
CREATE INDEX IF NOT EXISTS idx_transactions_category_code ON public.transactions (category_code);
CREATE INDEX IF NOT EXISTS idx_transactions_account_code ON public.transactions (account_code);
CREATE INDEX IF NOT EXISTS idx_transactions_referral_type ON public.transactions (referral_type);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON public.transactions (transaction_type);

-- Index Referensi & Master Data
CREATE INDEX IF NOT EXISTS idx_areas_area_code ON public.areas (area_code);
CREATE INDEX IF NOT EXISTS idx_coa_account_code ON public.chart_of_accounts (account_code);
CREATE INDEX IF NOT EXISTS idx_trx_categories_code ON public.transaction_categories (category_code);
CREATE INDEX IF NOT EXISTS idx_products_sku_code ON public.products (sku_code);
CREATE INDEX IF NOT EXISTS idx_customers_code ON public.customers (customer_code);
CREATE INDEX IF NOT EXISTS idx_suppliers_code ON public.suppliers (supplier_code);

-- Index Warta & Proyek
CREATE INDEX IF NOT EXISTS idx_news_articles_status ON public.news_articles (status);
CREATE INDEX IF NOT EXISTS idx_news_articles_tanggal ON public.news_articles (tanggal DESC);
CREATE INDEX IF NOT EXISTS idx_news_articles_kategori ON public.news_articles (kategori);
CREATE INDEX IF NOT EXISTS idx_project_updates_project_id ON public.project_updates (project_id);

-- Index Audit & RBAC
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.audit_logs (entity, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);
